add_executable(axiom_core_test core_test.cpp)
axiom_configure_language_diagnostics(axiom_core_test)
axiom_configure_static_analyzers(axiom_core_test)
axiom_configure_sanitizers(axiom_core_test)
axiom_configure_coverage(axiom_core_test)
axiom_configure_mutation_testing(axiom_core_test)
target_compile_features(axiom_core_test PRIVATE cxx_std_20)
target_link_libraries(axiom_core_test PRIVATE Axiom::Core)

add_test(NAME axiom.core COMMAND axiom_core_test)
if (AXIOM_COVERAGE)
    set_tests_properties(axiom.core PROPERTIES ENVIRONMENT "LLVM_PROFILE_FILE=axiom-%p-%m.profraw")
endif ()
axiom_configure_sanitizer_runtime(axiom_core_test)
