cmake_minimum_required(VERSION 3.25)

# A score based only on instantiated headers must never pass as Core coverage.
file(READ "${AXIOM_REPORT}" report)
string(JSON file_count LENGTH "${report}" files)
set(implementation_mutants 0)
if (file_count GREATER 0)
    math(EXPR last "${file_count} - 1")
    foreach (index RANGE 0 ${last})
        string(JSON source MEMBER "${report}" files ${index})
        string(REPLACE "\\" "/" normalized_source "${source}")
        if (normalized_source MATCHES "/src/core/src/.*[.]cpp$")
            string(JSON count LENGTH "${report}" files "${source}" mutants)
            math(EXPR implementation_mutants "${implementation_mutants} + ${count}")
        endif ()
    endforeach ()
endif ()
if (implementation_mutants EQUAL 0)
    message(FATAL_ERROR "Mull report has no Core implementation mutants; check library discovery")
endif ()
message(STATUS "Verified ${implementation_mutants} Core implementation mutants")
